name: Build and Publish
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > release.keystore.asc
          gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" --batch release.keystore.asc > app/release.keystore
          echo "${{ secrets.GOOGLE_SERVICES }}" > app/google-services.json.b64
          base64 -d app/google-services.json.b64 > app/google-services.json
          chmod +x gradlew
      - name: Install NDK
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build release
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          NCP_CLIENT_ID: ${{ secrets.NCP_CLIENT_ID }}
          NCP_CLIENT_SECRET: ${{ secrets.NCP_CLIENT_SECRET }}
      - uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: app-release
      - run: |
          ls -R
      - uses: actions/setup-node@v2-beta
      - name: Install firebase-tools
        run: npm install firebase-tools
      - name: Upload release to Firebase App Distribution
        run: |
          npx firebase appdistribution:distribute app-release.apk \
          --groups "default" \
          --token ${{ secrets.FIREBASE_TOKEN }} \
          --app ${{ secrets.FIREBASE_APP_ID }} \
